name: CI

on: [push, pull_request]

#on:
#  push:
#    branches: ["master"]
#  pull_request:
#    branches: ["master"]

jobs:
  tests:
    runs-on: ${{ matrix.platform }}
    # runs-on: "ubuntu-latest"
    # runs-on: macos-10.15
    name: "Python ${{ matrix.python-version }}"
    env:
      USING_COVERAGE: '3.8'

    strategy:
      matrix:
        # platform: [ubuntu-latest, macos-latest, windows-latest]
        platform: [macos-10.15]
        # Tox py39 environments run locally.. but
        # actually maybe 3.9 has some problem with pytables?
        # https://github.com/freqtrade/freqtrade/issues/4162

        # python-version: ["3.7", "3.8", "3.9"]
        python-version: ["3.7", "3.8"]

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v1"
        with:
          python-version: "${{ matrix.python-version }}"
          # python-version: "3.8"
      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools
          python -m pip install --upgrade coverage[toml] virtualenv tox tox-gh-actions tox-wheel
      - name: "Run tox targets for ${{ matrix.python-version }}"
        run: "python -m tox"
        # run: tox --wheel
#        env:
#          PLATFORM: ${{ matrix.platform }}

      - name: "Get coverage"
        run: |
          set -xe
          python -m coverage combine
          python -m coverage xml
        if: "contains(env.USING_COVERAGE, matrix.python-version)"
      - name: Upload coverage to Codecov
        if: "contains(env.USING_COVERAGE, matrix.python-version)"
        uses: "codecov/codecov-action@v1"
        with:
          fail_ci_if_error: true